min_version_sdk:
  description: |
    min version of SDK
  in: header
  required: true
  type: string
max_version_sdk:
  description: |
    max version of SDK
  in: header
  required: true
  type: string
version_sdk:
  description: |
    version of SDK
  in: header
  required: true
  type: string
token_user:
  description: |
    user
  in: body
  required: true
  type: string
token_password:
  description: |
    password
  in: body
  required: true
  type: string
userid_body:
  description: |
    guests userid
  in: body
  required: true
  type: string
guest_list:
  description: |
    guests list
  in: body
  required: true
  type: list
guest_userid:
  description: |
    guest userid
  in: path
  required: true
  type: string
guest_vcpus:
  description: |
    amount of vcpus
  in: body
  required: true
  type: integer
guest_memory:
  description: |
    size of memory in MB
  in: body
  required: true
  type: integer
guest_memory_kb:
  description: |
    size of memory in KB
  in: body
  required: true
  type: integer
guest_vnics:
  description: |
    vNICs statistics of one guest
  in: body
  required: true
  type: dict
guest_nic_info:
  description: |
    vNIC and vswitch pair of guest
  in: body
  required: true
  type: dict
guest_info:
  description: |
    status of guest
  in: body
  required: true
  type: integer
user_profile_guest:
  description: |
    profile of guest
  in: body
  required: false
  type: string
user_direct_guest:
  description: |
    user direct of guest
  in: body
  required: false
  type: string
disk_list_guest:
  description: |
    disk list of guest
    It has one dictionary that contain some of the below keys for
    each disk, the root disk should be the first element in the
    list.
  in: body
  required: false
  type: list
userid_list_guest:
  description: |
      a single userid string or a list of guest userids
  in: body
  required: true
  type: list
cpu_info_guest:
  description: |
    cpu statics of guest
  in: body
  required: true
  type: dict
power_status_guest:
  description: |
    power status of guest ,**on** or **off**
  in: body
  required: true
  type: string
cpu_time_us_guest:
  description: |
    cpu time(US) of guest
  in: body
  required: true
  type: time
num_cpu_guest:
  description: |
    cpu time(US) of guest
  in: body
  required: true
  type: integer
action_on_guest:
  description: |
    operation on one guest, include **start**, **stop**, **deploy**
    or **get-console-output** of guest.
  in: body
  required: true
  type: dict
vdev_guest:
  description: |
    nic device number, 1- to 4- hexadecimal digits
  in: path
  required: true
  type: string
