#!/bin/sh
# Copyright 2017 IBM Corp.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#
#------------------------------------------------------------------------------
# Checkout, compile, and build RPM for zThin RPM
#
# This bash script will:
#    -create a local git repo of the zThin source code.
#    -compile, link, and make an RPM of the c files using rpmbuild
#
# Example: buildzthingithub master
#
# The code is stored on https://github.com/mfcloud/python-zvm-sdk.git
# Code reviews are done using gerrithub:
#    https://review.gerrithub.io/#/q/project:mfcloud/python-zvm-sdk
#
# -----------------------------------------------------------------------------
if [[ -z "$1" ]]; then
   {
   echo "A branch must be specified"
   exit 1
   }
fi

BRANCH=$1
BUILD=/root/zthin-build
REPO=https://github.com/mfcloud/python-zvm-sdk.git
REPOTOP=python-zvm-sdk
ZTHINTOP=zthin-parts
SMCLIOPTDIR=/opt/zthin/bin/smcli

EXISTS=$(git ls-remote -h $REPO | grep "$BRANCH"$ | wc -l )
if [ "$EXISTS" == 0 ] ; then
   {
   echo "Branch $BRANCH does not exist on /mfcloud/python-zvm-sdk"
   echo "Try choosing one of the following branches:  "
   git ls-remote --heads $REPO | awk -F "heads/" '{print $2}'
   exit 1
   }
fi

# Prepare environment
rm -rf $BUILD/variable 2>/dev/null
mkdir -p $BUILD/variable 2>/dev/null
echo "%_topdir $BUILD" > $BUILD/variable/.rpmmacros
cp $BUILD/variable/.rpmmacros $HOME 2>/dev/null

# Create build directories
cd $BUILD/ 2>/dev/null
rm -rf $BUILD/BUILD 2>/dev/null
rm -rf $BUILD/RPMS 2>/dev/null
rm -rf $BUILD/SRPMS 2>/dev/null
mkdir -p $BUILD 2>/dev/null
mkdir -p $BUILD/BUILD 2>/dev/null
mkdir -p $BUILD/RPMS 2>/dev/null
mkdir -p $BUILD/SOURCES 2>/dev/null
mkdir -p $BUILD/SPECS 2>/dev/null
mkdir -p $BUILD/SRPMS 2>/dev/null
mkdir -p $BUILD/OUTPUT 2>/dev/null
mkdir -p $SMCLIOPTDIR 2>/dev/null

# Checkout the branch
echo "===>Erasing old $REPOTOP, then cloning: $REPO -b $BRANCH"
rm -rf ./$REPOTOP
git clone $REPO -b $BRANCH

# Move to the sdk directory
cd $REPOTOP 2>/dev/null

echo "===>compress zthin sourcefiles to $BUILD/SOURCES/zthin-build.tar.gz"
pwd
# Compress zThin source
tar czf $BUILD/SOURCES/zthin-build.tar.gz $ZTHINTOP
cp ./$ZTHINTOP/zthin.spec $BUILD/SPECS

echo "===>Switch back to zthin-parts, do: rpmbuild -ba -v $BUILD/SPECS/zthin.spec"
cd $BUILD/$REPOTOP/$ZTHINTOP 2>/dev/null
pwd
rpmbuild -ba -v $BUILD/SPECS/zthin.spec

echo "===> Copy over RPMs into /srv/ftp/zthin/$BRANCH/"
rm -rf /srv/ftp/zthin/$BRANCH/
mkdir -p /srv/ftp/zthin/$BRANCH/
cp -R $BUILD/RPMS/* /srv/ftp/zthin/$BRANCH/
mkdir -p $BUILD/OUTPUT/$BRANCH 2>/dev/null
cp -R $BUILD/RPMS/s390x/* $BUILD/OUTPUT/$BRANCH
cp -R $BUILD/SRPMS/* $BUILD/OUTPUT/$BRANCH


# Erase build directories under /var/tmp
rm -rf /var/tmp/zthin-*
