#!/bin/sh
# Copyright 2017 IBM Corp.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#
#------------------------------------------------------------------------------
# compile, and build RPM for zThin RPM
#
# This bash script will:
#    -compile, link, and make an RPM of the c files using rpmbuild
#
# Note:
#     The code must previously been extracted and stored in $BUILD directory
#     by running buildzthingithub script first
#
# Example: compilezthinonly
#
# The code is stored on https://github.com/mfcloud/python-zvm-sdk.git
# Code reviews are done using gerrithub:
#    https://review.gerrithub.io/#/q/project:mfcloud/python-zvm-sdk
#
# -----------------------------------------------------------------------------
BUILD=/root/zthin-build
REPOTOP=python-zvm-sdk
ZTHINTOP=zthin-parts
BRANCH=nobranch
SMCLIOPTDIR=/opt/zthin/bin/smcli
# Reset build directories
cd $BUILD/ 2>/dev/null
rm -rf $BUILD/BUILD 2>/dev/null
rm -rf $BUILD/RPMS 2>/dev/null
rm -rf $BUILD/SRPMS 2>/dev/null
rm -rf $BUILD/SOURCES 2>/dev/null
mkdir -p $BUILD/BUILD 2>/dev/null
mkdir -p $BUILD/RPMS 2>/dev/null
mkdir -p $BUILD/SRPMS 2>/dev/null
mkdir -p $BUILD/SOURCES 2>/dev/null
mkdir -p $BUILD/SPECS 2>/dev/null
mkdir -p $BUILD/SRPMS 2>/dev/null
mkdir -p $BUILD/OUTPUT 2>/dev/null
mkdir -p $SMCLIOPTDIR 2>/dev/null

# Move to the sdk directory
cd $REPOTOP 2>/dev/null

# Compress zThin source
tar czf $BUILD/SOURCES/zthin-build.tar.gz $ZTHINTOP
cp ./$ZTHINTOP/zthin.spec $BUILD/SPECS

echo "===>Switch to $ZTHINTOP, do: rpmbuild -ba -v $BUILD/SPECS/zthin.spec"
cd $BUILD/$REPOTOP/$ZTHINTOP 2>/dev/null
pwd
rpmbuild -ba -v $BUILD/SPECS/zthin.spec

echo "===> Copy over RPMs into /srv/ftp/zthin/$BRANCH/"
rm -rf /srv/ftp/zthin/$BRANCH/
mkdir -p /srv/ftp/zthin/$BRANCH/
cp -R $BUILD/RPMS/* /srv/ftp/zthin/$BRANCH/
mkdir -p $BUILD/OUTPUT/$BRANCH 2>/dev/null
cp -R $BUILD/RPMS/s390x/* $BUILD/OUTPUT/$BRANCH
cp -R $BUILD/SRPMS/* $BUILD/OUTPUT/$BRANCH


# Erase build directories under /var/tmp
rm -rf /var/tmp/zthin-*
