#!/bin/sh
# IBM(c) 2017 EPL license http://www.eclipse.org/legal/epl-v10.html
#------------------------------------------------------------------------------
# compile, and build RPM for zHCP RPM
#
# This bash script will:
#    -compile, link, and make an RPM of the c files using rpmbuild
#
# Note:
#     The code must previously been extracted and stored in $BUILD directory
#     by running buildzhcpgithub script first
#
# Example: compilezhcponly
#
# The code is stored on https://github.com/zVMopenstack/zhcp
# Code reviews are done using gerrithub:
#   https://review.gerrithub.io/#/q/project:zVMopenstack/zhcp
#
# -----------------------------------------------------------------------------
BUILD=/root/zhcp-build
# Reset build directories
cd $BUILD/ 2>/dev/null
rm -rf $BUILD/BUILD 2>/dev/null
rm -rf $BUILD/RPMS 2>/dev/null
rm -rf $BUILD/SRPMS 2>/dev/null
rm -rf $BUILD/SOURCES 2>/dev/null
mkdir -p $BUILD/BUILD 2>/dev/null
mkdir -p $BUILD/RPMS 2>/dev/null
mkdir -p $BUILD/SRPMS 2>/dev/null
mkdir -p $BUILD/SOURCES 2>/dev/null
mkdir -p $BUILD/SPECS 2>/dev/null
mkdir -p $BUILD/SRPMS 2>/dev/null
mkdir -p $BUILD/OUTPUT 2>/dev/null

# Compress zHCP source
tar czf $BUILD/SOURCES/zhcp-build.tar.gz zhcp
cp ./zhcp/zhcp.spec $BUILD/SPECS

# Build ZHCP package
rpmbuild -ba -v $BUILD/SPECS/zhcp.spec

# Copy over RPMs into /srv/ftp
rm -rf /srv/ftp/zhcp/$BRANCH/
mkdir -p /srv/ftp/zhcp/$BRANCH/
cp -R $BUILD/RPMS/* /srv/ftp/zhcp/$BRANCH/
mkdir -p $BUILD/OUTPUT/$BRANCH 2>/dev/null
cp -R $BUILD/RPMS/s390x/* $BUILD/OUTPUT/$BRANCH
cp -R $BUILD/SRPMS/* $BUILD/OUTPUT/$BRANCH


# Erase build directories under /var/tmp
rm -rf /var/tmp/zhcp-*
