name: Pull Request Check Test
on:
  pull_request:
    branches: [ master ]
jobs:
  python:
    name: python checks ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox>=3.23.1
    - name: PEP8
      run: tox -e pep8
    - name: unit test
      run: tox -e py311
